DROP TABLE IF EXISTS OrderProduct;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS ProductIngredient;
DROP TABLE IF EXISTS Vehicles;
DROP TABLE IF EXISTS Drivers;
DROP TABLE IF EXISTS Clients;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Ingredients;